{% set name = "openawsem" %}
{% set version = "1.1.1" %}

package:
  name:  {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/npschafer/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: d43deb8a6704642ee36cc52e943a4529fd9c675d7944981a658a8ce9749bfcff

build:
  number: 0
  noarch: python
  entry_points:
  - awsem_create = openawsem.scripts.mm_create_project:main
  - awsem_run = openawsem.scripts.mm_run:main
  - awsem_analyze = openawsem.scripts.mm_analyze:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python >=3.8
  run:
    - python >=3.8
    - biopython
    - matplotlib-base
    - numpy
    - pandas
    - openmm
    - pdbfixer
    - mdtraj

test:
  imports:
    - openawsem
  commands:
    - awsem_create


about:
  home: https://openawsem.org/
  summary: 'Implementation of the AWSEM protein forcefield in OpenMM'
  description: "An Implementation of the AWSEM coarse-grained protein folding forcefield in OpenMM."
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://openawsem.org/
  dev_url: https://github.com/npschafer/openawsem

extra:
 recipe-maintainers:
    - cabb99
